### ISSUE TITLE
pod 'Buckets' library for swift 3

### ISSUE THREAD

**Issue by AreejQudi** [mauriciosantos/Buckets-Swift#3]
Hi , 
I'm trying to update my pod file for swift 3 
I need the updated command of pod 'Buckets', '~> 1.1'

**Comment by mauriciosantos** [comment]
Hi,

As you probably know Swift 3 is not backwards compatible with Swift 2. So you can not use this library in swift 3 projects using cocoapods yet. I expect to release an updated version shortly.

**Comment by AreejQudi** [comment]
waiting for this
thank you

**Comment by mauriciosantos** [comment]
Hi,

I release an update yesterday which makes the library compatible with Swift 3. This should fix your problem.

**Comment by AreejQudi** [comment]
Thank you

**Comment by AreejQudi** [comment]
Thank you

**Comment by AreejQudi** [comment]
Hey,
I got this problem

[!] Unable to satisfy the following requirements:

   - Buckets (~> 2.0) required by Podfile

**Comment by mauriciosantos** [comment]
I updated the README file with the coocapods instructions. Please try again.
